name: Generate Semantic Release
on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  call-workflow-passing-data:
    uses: Sanket322/testing/.github/workflows/on_release.yml@main
    with: 
      git_author_name: "Frappe PR Bot"
      git_author_email: "developers@frappe.io"
      git_committer_name: "Frappe PR Bot"
      git_committer_email: "developers@frappe.io"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
