name: Server Tests
on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  call-workflow-passing-data:
    uses: Sanket322/india_compliance/.github/workflows/server-tests.yml@Reusable_Workflow
    with: 
      base_ref: "hello"
      repo_name: "repo name"
