name: Server Tests
on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:
  call-workflow-passing-data:
    uses: Sanket322/india-compliance/.github/workflows/server-tests.yml@Reusable_Workflow
    with: 
      base_ref: "hello"
      repo_name: ${{ github.event.repository.name }}
    # secrets: 
      # callers_codecov_token: ${{ secrets.GITHUB_TOKEN }}
      # callers_codecov_token: ${{  secrets.RELEASE_TOKE  }}
      # callers_codecov_token: ${{ secrets.GITHUB_TOKEN  }}
      # callers_codecov_token: ${{ secrets.CODECOV_TOKEN  }}
